### ISSUE TITLE
Odd behavior with some color schemes

### ISSUE THREAD

**Issue by edheltzel** [vprimachenko/Sublime-Colorcoder#14]
This seem to happen on a variety of color schemes Not sure what the issue is.
![screenshot 2014-04-28 17 42 47](https://cloud.githubusercontent.com/assets/402910/2823351/17e7408e-cf1e-11e3-912b-f9ad499b7133.png)

**Comment by vprimachenko** [comment]
It seems colorcoder was either not able to modify the color sceme or to apply it. What it the real value of `"color_scheme"` in `Preferences.sublime-settings`?

**Comment by edheltzel** [comment]
there is actually only one value for `color_scheme` 
`"color_scheme": "Packages/User/Dark Neon (SL).tmTheme",`

There was at one point two, I did try switching the color scheme and still only one value shows up.

**Comment by vprimachenko** [comment]
please check if colorcoder was successfull at creating an own `Sublime Text 3\Data\Packages\Colorcoder` folder and created modified color scemes there. Also are 'colorcoded' scemes present in the the `preferences`>`color scemes` menu?

**Comment by edheltzel** [comment]
I uninstalled and installed again... still the same result, though its only on a few different themes.

**Comment by Cubox** [comment]
I have the same problem, here is the error in the console. 

```
Traceback (most recent call last):
  File "colorcoder in /Users/cubox/Library/Application Support/Sublime Text 3/Installed Packages/Colorcoder.sublime-package", line 67, in read_settings
  File "colorcoder in /Users/cubox/Library/Application Support/Sublime Text 3/Installed Packages/Colorcoder.sublime-package", line 77, in maybefixscheme
  File "colorcoder in /Users/cubox/Library/Application Support/Sublime Text 3/Installed Packages/Colorcoder.sublime-package", line 127, in modify_color_scheme
KeyError: 'background'
```

Using the Solarized package.

**Comment by ctf0** [comment]
have the same problem.

**Comment by vprimachenko** [comment]
@Cubox- could you link me the scheme? dropbox or gist…

**Comment by Cubox** [comment]
It's packaged in Sublime Text I think...

Solarized Dark.

**Comment by edheltzel** [comment]
@vprimachenko Just confirming that this did fix my issue Dark Neon theme.  Thanks!

**Comment by ctf0** [comment]
much thankful for the fix ,btw is it possible to only make CC apply its high lighting only when the theme is applied ,i mean i have a plugin call ColorSchemeSelector which makes it easier to preview all the skins u have then chose the one u want) the problem is when ColorCoder is enabled it keeps making clones of the first skin u chose and basically every time u chose a one it clones it self over and over again.

**Comment by vprimachenko** [comment]
@ctf0 just set `auto_apply_on_scheme_change` to `false` and add the colorcoded schemes to the `ColorSchemeSelector`

**Comment by ctf0** [comment]
setting auto apply to false has no effect ,i have to use ignore packages ,also colorcode schemes are added automatically to the ColorSchemeSelector ,that's why it keeps cloning it self.

Update:
the cloning issue was related to colorhighlighter ,now its fixed.

one last thing ,could u plz check the scheme call (Brilliance Black by Thomas Aylott) basically all of his themes have the same behavior with CC as mentioned at the first post.
