### ISSUE TITLE
Preserve Font Weight

### ISSUE THREAD

**Issue by Sawtaytoes** [vprimachenko/Sublime-Colorcoder#34]
Is it possible when coloring to preserve the font weight? I've noticed on Solarized Dark in HTML, my tags are bold when using the default but the modified isn't like that. I'm assuming this would require you know the weight of that item in the syntax specs sheet prior to overriding it.

**Comment by vprimachenko** [comment]
you are right, colorcoder would need to examine what font weights are used.

the reason this does not work "as is" is same api issue as in #32 - styles dont stack, and if then in mysterious (and undocumented) ways

now you could fix the scheme yourself, or modify the plugin to e.g. make all colorcoded names bold (on theme modification, just add the according definition after [line `211`](https://github.com/vprimachenko/Sublime-Colorcoder/blob/master/colorcoder.py#L211)).

How i could examine the scheme file and use those settings but for cases where variable names are bold but function calls are not colorcoder would need elaborate logic in main loop (which has to be fast so the editor don't lag): it would need to examine tokens scope and add region with different scope accordingly. Now the scope names used are `cc0x00`…`cc0xff`, in described case there would be `cc0x00-variable`, `cc0x00-functionname`, and now imagine different languages would have own styles as well, or global variables are bold and local are not. I double i could even write code which could find all this different situations from a scheme file, and even when the modified scheme would be enormous and the user would experience a noticeable lag

i am sorry to decline yet another feature request as `can't fix because api, can't workaround bc lag` but the only hope for proper solution is for sublime developers to make the styles work more like css styles do
