### ISSUE TITLE
Python colorcoding broken?

### ISSUE THREAD

**Issue by objarni** [vprimachenko/Sublime-Colorcoder#37]
I was under the impression the color coding was supposed to identify variables ('names' in Python lingua) and not whole rows? This just looks weird....
![colorcoderpythonst3](https://cloud.githubusercontent.com/assets/68198/4950328/a4596e8e-6659-11e4-845c-16f987e3e86a.png)

OS: Ubuntu 14.04 64-bit
Software: Sublime Text 3
Install: via package control

**Comment by objarni** [comment]
I get the same problem in C++; keywords and method names are colored, but not local variables. Is this expected behaviour?

**Comment by objarni** [comment]
OK I found this thread on the Sublime Text forum, that gave me the solution: via command palette choose syntax highlighter. Is it not possible for Colorcoder to do this automatically, on detecting what language is used in the buffer?

**Comment by vprimachenko** [comment]
this is expected behaviour (or better, i expect the user to change the language manually or set them as default) as default languages don't provide the needed level of fidelity in terms of token distinction – hence i provide special colorcoded languages (as noted in readme).

Theoretically it is possible for colorcoder to automatically switch the definitions, but i restrained from implementing this as:
- the user can simply set the colorcoded languages as default for filetype via `language menu`▶`Open all with current extension as`▶`Colorcoder`▶`… (Colorcoded)`
- this functionality would interfere with other appropiate-syntax-select plugins like excellent  [ApplySyntax](https://github.com/facelessuser/ApplySyntax)
- because of bugs like #9 i prefer to leave the choice to the user

**Comment by objarni** [comment]
Thank you!

I will definitely go for the default language for extension as I already - after using this only for a day - feel in better control of my code - this package enhances "local readability" for a method a lot. 

By reading through the whole doc page I see this is documented under the header "Supported languages". I would have expected this to be part of the header "Installation" as I expect plugins to start working once installed (after a ST reboot at least), or if anything like this is necessary to set them up, I expect it to be documented under "Installation".

Thanks for a great plugin!
