### ISSUE TITLE
Does not work for CS

### ISSUE THREAD

**Issue by xixixao** [vprimachenko/Sublime-Colorcoder#54]
Well, I am getting bogus highlighting. I am using the correct syntax highlighting packaged with Colorcoder, and installed Colorcoder from Package Control.

<img width="470" alt="screenshot 2015-09-15 12 03 37" src="https://cloud.githubusercontent.com/assets/1473433/9992807/9f2417b4-6074-11e5-80f4-c17d2a1d197b.png">

Are there any known clashes? I'd really like to try this out!

**Comment by vprimachenko** [comment]
your picture is not loading

**Comment by xixixao** [comment]
Fixed.

**Comment by dungsaga** [comment]
Built-in JavaScript syntax is not compatible with new ES6 syntax. You need to install package **Babel** and choose `Open all with current extension as...` > `Babel` > `JavaScript (Babel)`

**Comment by vprimachenko** [comment]
@xixixao please check if @dungsaga's solution works, i will add babel as recommended package to readme then

**Comment by xixixao** [comment]
@dungsaga @vprimachenko CoffeeScript has nothing to do with ES6

**Comment by dungsaga** [comment]
@xixixao Sorry, I didn't notice this is CoffeeScript code.
I think the problem is in built-in syntax package for CoffeeScript.
- Set up Ctrl+F12 to view the scope of any text at cursor position (see readme.md of Colorcoder)
- You can see the scope of an assignment operator in CoffeeScript is `source.coffee variable.assignment.coffee variable.other.coffee keyword.operator.coffee` and the scope of the variable on its left side is `source.coffee variable.assignment.coffee variable.other.coffee`
- Colorcoder default setting includes scope `variable.other`, that's why `compiler =` is colorized as one word
- In contrast, in Javascipt (Babel), scopes are `source.js keyword.operator.assignment.js` and `source.js variable.other.readwrite.js` respectively
